from .home import *
from .users import *
from .contact import *
from .videosctrl import *
from .commonctrl import *
from .tracksctrl import *
from .albumctrl import *
from .searchctrl import *
from .likectrl import *
from .explorectrl import *