# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-12 06:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(null=True)),
                ('month', models.TextField(null=True)),
                ('year', models.TextField(null=True)),
                ('gender', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('picture', models.ImageField(null=True, upload_to='media')),
                ('medium_pic', models.TextField(blank=True, null=True)),
                ('thumbnail_pic', models.TextField(blank=True, null=True)),
                ('isfeatured', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(null=True)),
                ('city', models.TextField(null=True)),
                ('state', models.TextField(null=True)),
                ('country', models.TextField(null=True)),
                ('website', models.TextField(null=True)),
                ('phone', models.TextField(null=True)),
                ('reason', models.TextField(null=True)),
                ('activateit', models.TextField(blank=True, null=True)),
                ('forgotstr', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
