# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-12 07:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dob',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
