# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-13 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0010_auto_20170613_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='cms',
            name='picture',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
