# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0015_emailtemplates_genre_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('contactno', models.CharField(blank=True, max_length=100, null=True)),
                ('feedback_text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
