# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-22 06:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0016_auto_20170616_0543'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
