# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0017_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
