# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0018_video_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='artist',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='is_approved',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
