# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 12:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0019_auto_20170630_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.Genre'),
        ),
        migrations.AlterField(
            model_name='video',
            name='types',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.Type'),
        ),
        migrations.AlterField(
            model_name='video',
            name='uploadby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
