# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0020_auto_20170630_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='link_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
