# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0021_video_link_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='artist',
        ),
    ]
