# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0026_userprofile_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='like_counts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tracks',
            name='like_counts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='like_counts',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
