# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0032_countries_states'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
