# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0033_userprofile_phone_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='most_browsed',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
