# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 05:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0037_userprofile_is_loggedin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='is_deleted',
        ),
    ]
