# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0040_auto_20170816_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='is_deleted',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
