# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0041_messages_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='is_deleted',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
    ]
