# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0043_remove_messages_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='is_deleted_msg',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='messages',
            name='is_deleted_thread',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
    ]
