# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0045_messages_is_new_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='is_read_to',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
    ]
